### ISSUE TITLE
issues with mkoverride.sh

### ISSUE THREAD

**Issue by Baerbeisser** [lorenz/asrock-x300-s3-fix#9] opened 2023-07-26 14:09 UTC
PC: Deskmini X300
APU: 5700G
OS: Artix Linux (Arch with other init)
Bios-Version:  P1.80F

First, the failing `0001-bump-version.patch` stops the whole loop.
To make it work with `P1.80F`, i guess i have to change the date line in the patch? The DefinitionBlock too? And to what?

I saw the comment of felicia-wen in the [other issue](https://github.com/lorenz/asrock-x300-s3-fix/issues/6#issuecomment-1497381695) but that doesn't help me anything, i don't know much about SSDT/DSDT or opencore. Can *you* extract the neccessary data from it?

Second, i have no `gen_init_cpio`, pkgfile doesn't find any package containing it, should that be  a function? Which, i guess, creates the final `acpi_dsdt_override.cpio`.
Well, currently,`bash: gen_init_cpio: command not found`

**Comment by lorenz** [comment] 2023-08-06 12:46
This is basically a duplicate of #6, there is currently no support for the 1.80 firwmare. I currently don't run that firmware, so I don't have the necessary DSDT. You can attach your DSDT to the other issue, then I can take a look. If you do not know what you are doing please just use the Nix setup which contains all the right software and patches. It will also work on Arch.

**Closed as not planned by lorenz** 2023-08-06 12:46 UTC
